version: '3.8'

services:
  app:
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=$USER_UID
        - USER_GID=$USER_GID
        - USERNAME=$USERNAME
    volumes:
      - .:/ros2_ws # 左側にある方のファイルを右側にある方のファイルにマウントする
    working_dir: /ros2_ws # コンテナ内での作業ディレクトリ(ここで指定したらDockerfileのWORKDIRは無視される)
    container_name: "navigation_server"
    user: "${USER_UID}:${USER_GID}"